### PR TITLE
Fixed Enchantments

### PR DESCRIPTION
**Pull request by j0ach1mmall3**

### CODE REVIEW

**Comment by samczsun** [comment]
:-1: No one likes Bane of Arthropods

**Comment by TheLightMC** [comment]
:-1: You can't go and make up an enchantment Mr. DEPTH_STRIDER

**Comment by Fireflies** [comment]
Mind creating a constructor that accepts a single `Material` and delegates to the one accepting a collection?

**Comment by j0ach1mmall3** [comment]
> You can't go and make up an enchantment Mr. DEPTH_STRIDER

I would like to point out to mr Nathan that, according to the pocket edition wiki, there is an enchantment called DEPTH_STRIDER
(http://minecraftpocketedition.wikia.com/wiki/Enchanting)

**Comment by TheLightMC** [comment]
Stop spoofing pls

**Comment by j0ach1mmall3** [comment]
> Stop spoofing pls

Spoofing what? Spoofing enchantments? If the minecraft pocket edition wik is wrong, then you should go complain there. But as long as it's listed there, I'll add it in the class

**Pull request merged**
