### PR TITLE
Don't neglect SnowGolems (added)

### PR DESCRIPTION
**Pull request by WeeSkilz**

### CODE REVIEW

**Comment by Serializator** [comment]
We hate Snow Golems!

**Comment by j0ach1mmall3** [comment]
Since when are Snow Golems Hostile though?

**Comment by WeeSkilz** [comment]
They attack other `LivingEntity`s so they are hostile.

**Comment by Serializator** [comment]
The type is "Neutral" over here?
http://minecraftpocketedition.wikia.com/wiki/Snow_Golem

**Comment by WeeSkilz** [comment]
@Serializator so is Enderman however it falls under Hostile in our code

**Comment by j0ach1mmall3** [comment]
> @Serializator so is Enderman however it falls under Hostile in our code

That's cause our code atm is flawed

**Comment by Serializator** [comment]
I can't disagree with that @j0ach1mmall3.

**Comment by j0ach1mmall3** [comment]
> I can't disagree with that @j0ach1mmall3.

@Fireflies will probably unfuck it anyways :^)

**Comment by TheLightMC** [comment]
These should be neutral.

**Comment by Fireflies** [comment]
Neutral is pointless. Either use default behaviour or be a dick to that poor Sheep in the corner.

**Pull request merged**
