### PR TITLE
Added ExperienceOrb and Item implementation

### PR DESCRIPTION
**Pull request by j0ach1mmall3**
Added Multi-world support
Added Entities list in World

### CODE REVIEW

**Comment by TheLightMC** [comment]
I think that the Dimension method shouldn't be used for the over world/nether. It gives the false impressions of the boundaries in my own opinion.

**Comment by j0ach1mmall3** [comment]
Mhmm, what do you suggest?

**Comment by nickrobson** [comment]
@TheLightMC Minecraft's term for Overworld/Nether/The End is "Dimension", so it should be used.

Bounds should instead be represented by a "WorldSize", "WorldBounds" or "Bounds".

**Comment by WeeSkilz** [comment]
I suggest leaving Dimension, it's the term Minecraft uses internally to describe predetermined worlds OVERWORLD/NETHER/END

It has connotations of Generation as well.

**Comment by TheLightMC** [comment]
In that case I agree that we should remain with Dimension @WeeSkilz . My bad @j0ach1mmall3.

**Pull request closed without merging**
