### PR TITLE
Added DirectionalLocation

### PR DESCRIPTION
**Pull request by j0ach1mmall3**
Added setters for Location and DirectionalLocation
Something with clone and stuff

### CODE REVIEW

**Comment by Serializator** [comment]
What's the difference between 'yaw' and 'headYaw'?

**Comment by j0ach1mmall3** [comment]
Players have Head Yaw and Yaw, Entities only have Yaw
I'm not really sure what their purpose is, but it's in the protocol according to MiNET (https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol%20Documentation.md#package-mcpe-add-player-0x96)

**Comment by TheLightMC** [comment]
yaaa nooopppeeee

**Comment by TheLightMC** [comment]
You're lucky this ONE time. http://i.imgur.com/hzSFkVo.png

**Comment by Fireflies** [comment]
Nathan's rage

`/rage`

**Comment by Serializator** [comment]
Git CLI FOR THE WIN

**Comment by Fireflies** [comment]
:+1:

**Comment by j0ach1mmall3** [comment]
Lol

**Pull request merged**
