### PR TITLE
Removed the ZombieVillager interface and added a villager flag to the

### PR DESCRIPTION
**Pull request by Serializator**
Zombie interface.

Added Zombie#isVillager() and Zombie#setVillager().

### CODE REVIEW

**Comment by j0ach1mmall3** [comment]
Eww

**Comment by j0ach1mmall3** [comment]
Please no, it's more consistent to have a seperate ZombieVillager dince they have a seperate entity id. Wither skeletons don't have that.
Just my opinion

**Comment by nickrobson** [comment]
This is a fair point, but it just means more backend code. It's easier to use this API though, since ZombieVillager would just be an extension of Zombie, anyway.

**Comment by j0ach1mmall3** [comment]
Or just make
public interface ZombieVillager extends Zombie?

**Comment by nickrobson** [comment]
That still requires a tad more work.

**Comment by j0ach1mmall3** [comment]
I'd be happy to maintain that one class by myself if it means the consistency will be optimal ;)

**Comment by nickrobson** [comment]
It should really extend Villager AND Zombie, since it should be able to go ZombieVillager#cure() or whatever.. Hard stuff.

**Comment by j0ach1mmall3** [comment]
Well, otherwise you add that hard stuff just in the Zombie class, together with other stuff

**Comment by nickrobson** [comment]
You can't though, since it would need to become a Villager then..

**Comment by j0ach1mmall3** [comment]
Well how'd you do it then in the Zombie class (#setVillager)

**Comment by nickrobson** [comment]
No idea, haha.

**Pull request merged**
