### PR TITLE
API and Implementations for Entity API.

### PR DESCRIPTION
**Pull request by nickrobson**
Spawning of them will now create the correct entity classes.
Adds missing FallingBlock and PrimedTNT interfaces.
Adds missing Painting#setOrientation(Orientation).
Blaze now correctly inherits Flying.
PigZombie now correctly inherits Ageable.
Neutral is now in `org.pocketserver.api.entity.living`.
PigZombie is now in `org.pocketserver.api.entity.living.neutral`, as it is neutral.

### CODE REVIEW

**Comment by j0ach1mmall3** [comment]
:+1:

**Comment by nickrobson** [comment]
Failing because credentials are missing -- code is fine.

**Comment by Serializator** [comment]
@nickrobson, please read issue #56, you don't have to update this PR.

**Comment by nickrobson** [comment]
@Serializator This isn't an API PR: It's an implementation one. Please read.

**Comment by nickrobson** [comment]
@Fireflies pls

**Comment by nickrobson** [comment]
danke

**Pull request merged**
