### PR TITLE
Added HeadYaw parameter in Location (Needed in AddPlayer Packet)

### PR DESCRIPTION
**Pull request by j0ach1mmall3**

### CODE REVIEW

**Comment by Fireflies** [comment]
A `Location` does not necessarily describe the position of an `Entity`. It could be completely random, or it could be where to find Nathan's pot of gold.

**Comment by j0ach1mmall3** [comment]
Then the HeadYaw is 0? Just like the Yaw is also 0 at a Block Location?

**Comment by Fireflies** [comment]
Fair point, will consider moving.

**Comment by nickrobson** [comment]
This should be separate. Perhaps:
`class DirectionalLocation extends Location`
would work?

**Comment by Fireflies** [comment]
Makes more sense, will implement later today.

**Pull request closed without merging**
